title="Example Title"
subtitle="Example Sub-Title"
author="Example Writer"
authoremail="writer@example.com"
key="http://randomkeygen.com/"
tags="tags,for,search,engines"
description="Description of website for search engines"
